name: Selenium Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 5" # Runs every Friday midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn package

      - name: Run Selenium tests
        run: mvn test
